# Generated by Django 3.1.1 on 2024-04-08 15:56

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('team_name', models.CharField(max_length=255, verbose_name='Team Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='team_name', unique=True, verbose_name='Team Address')),
                ('created_date', models.DateField(blank=True, verbose_name='Date Created:')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
