# Generated by Django 3.1.1 on 2024-04-08 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('match_name', models.CharField(max_length=255, verbose_name='Match Name')),
                ('match_date', models.DateField(blank=True, verbose_name='Match Date')),
                ('created_date', models.DateField(blank=True, verbose_name='Date Created:')),
                ('team_id1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='nba.team')),
                ('team_id2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='nba.team')),
                ('winner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='nba.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
