# Generated by Django 3.1.1 on 2024-04-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
    ]
