# Generated by Django 3.1.1 on 2024-04-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_remove_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Points:'),
        ),
    ]
