# Generated by Django 3.1.1 on 2024-04-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0004_remove_match_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avg_assists',
            field=models.IntegerField(blank=True, null=True, verbose_name='Average Assists:'),
        ),
        migrations.AddField(
            model_name='team',
            name='avg_rebounds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Average Rebounds:'),
        ),
        migrations.AddField(
            model_name='team',
            name='avg_shootings',
            field=models.IntegerField(blank=True, null=True, verbose_name='Average Shootings:'),
        ),
        migrations.AddField(
            model_name='team',
            name='standings',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Standing:'),
        ),
    ]
